# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['due']},
        ),
        migrations.AddField(
            model_name='deadline',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Profile'),
            preserve_default=False,
        ),
    ]
