# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171118_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='user',
        ),
    ]
