# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_deadline_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Profile'),
        ),
    ]
