# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171118_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Profile'),
        ),
    ]
